export const GET_ARTISTS_ALL = 'GET_ARTISTS_ALL';
export const GET_ARTISTS_SEARCH = 'GET_ARTISTS_SEARCH';
export const GET_ARTISTS_DETAIL = 'GET_ARTISTS_DETAIL';
export const CLEAR_ARTIST_DETAIL = 'CLEAR_ARTIST_DETAIL';